"use client";

import { PenLine, FileText } from "lucide-react";

export default function DraftsTab() {
  return (
    <div className="flex-1 overflow-y-auto">
      <div className="px-4 py-4 md:py-6 md:max-w-2xl md:mx-auto space-y-3 md:space-y-4">
        <div>
          <h2 className="text-base font-semibold mb-1">Drafts &amp; Outputs</h2>
          <p className="text-xs md:text-sm text-text-secondary">
            Documents generated from your case materials.
          </p>
        </div>

        {/* Draft cards */}
        <div className="bg-surface-1 border border-border rounded-lg p-3 md:p-4 flex items-start gap-3 md:gap-4 hover:border-border-strong active:border-brand transition-colors cursor-pointer">
          <div className="size-9 rounded-lg bg-warning-bg flex items-center justify-center text-warning shrink-0">
            <PenLine size={18} />
          </div>
          <div className="flex-1 min-w-0">
            <h3 className="font-medium text-sm">Board Complaint — Draft v1</h3>
            <p className="text-xs text-text-disabled mt-0.5">12 pages · Last edited June 5</p>
          </div>
          <span className="text-xs px-2 py-0.5 rounded-sm bg-warning-bg text-warning shrink-0">
            Draft
          </span>
        </div>

        <div className="bg-surface-1 border border-border rounded-lg p-3 md:p-4 flex items-start gap-3 md:gap-4 hover:border-border-strong active:border-brand transition-colors cursor-pointer">
          <div className="size-9 rounded-lg bg-info-bg flex items-center justify-center text-info shrink-0">
            <FileText size={18} />
          </div>
          <div className="flex-1 min-w-0">
            <h3 className="font-medium text-sm">Case Screening Report</h3>
            <p className="text-xs text-text-disabled mt-0.5">5 sections · Generated June 5</p>
          </div>
          <span className="text-xs px-2 py-0.5 rounded-sm bg-success-bg text-success shrink-0">
            Complete
          </span>
        </div>

        <p className="text-xs text-text-disabled text-center pt-6">
          Drafts generated by the agent will appear here.
        </p>
      </div>
    </div>
  );
}
